version: '3.4'

services:
  tododb:
    container_name: tododb
    restart: always
    ports:
      - "27017:27107"
    volumes:
      - mongo_data:/data/db

  ballast.todo.api:
    container_name: ballast.todo.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://tododb:27017"
    depends_on:
      - tododb
    ports:
      - "8000:8080"